import js from '@eslint/js';
import tsEslint from 'typescript-eslint';
import security from 'eslint-plugin-security';

// Ported from the monorepo root config when this site was extracted. Two
// deliberate differences: `project` points at this repo's own tsconfig rather
// than the workspace glob, and the root's `eslint-plugin-import` import is
// dropped — it was declared there but never actually used in the config.
//
// Scope note: there is no Astro parser here, matching the monorepo. That means
// `eslint src` only lints the .ts files (src/data/integrations.ts, src/env.d.ts);
// the .astro pages are not linted. `astro check` (pnpm typecheck) is what covers
// those. Kept as-is on extraction rather than silently widening the gate.
export default tsEslint.config(
  js.configs.recommended,
  ...tsEslint.configs.strictTypeChecked,
  ...tsEslint.configs.stylisticTypeChecked,
  security.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        project: ['./tsconfig.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      'no-console': 'error',
    },
  },
  {
    ignores: ['dist/', 'node_modules/', '.astro/', '*.config.*'],
  },
  {
    // env.d.ts is auto-generated by `astro sync` and gets overwritten on every
    // sync, so any inline disable comment would get stripped. Disable the
    // triple-slash-reference rule for these specific files instead.
    files: ['src/env.d.ts'],
    rules: {
      '@typescript-eslint/triple-slash-reference': 'off',
    },
  }
);
